
language: cpp
sudo: false # only for faster builds
install:
  - sudo apt update && sudo apt -y install openscenegraph libopenscenegraph-dev libbullet-dev
script:
  - make -DNO_BTOSG_LOAD_OBJ test

after_success:
  - bash <(curl -s https://codecov.io/bash)
