
language: cpp
sudo: false # only for faster builds
install:
  - sudo apt update && sudo apt -y install openscenegraph libopenscenegraph-dev libbullet-dev
script:
  - make BTOSG_LOAD_OBJ=NO test
  - make manual
after_success:
  - bash <(curl -s https://codecov.io/bash)
